### ISSUE TITLE
TypeError from r20.js

### ISSUE THREAD

**Issue by BNoiZe** [Enigma644/R20Converter#3]
Hi,
I can't seem to get this tool to work. I'm always getting a type error in the javascript console and the download button is not appearing. I tried waiting for nearly an hour now.

```
[Error] TypeError: undefined is not an object (evaluating 'searchArray.length')
	(anonymous function) (r20.js:502)
	replace
	fixR20URLs (r20.js:490)
	onReaderLoad (r20.js:403)
```

**Comment by Enigma644** [comment]
Which module are you parsing?

**Comment by BNoiZe** [comment]
Was trying to parse Curse of Strahd.

**Comment by Enigma644** [comment]
Works for me.
Initial parse took 11 seconds,
Downloading the module took 2 minutes 10 seconds.

I tested using Chrome on Windows x64 with a Quad core i7 and 24GB of RAM.
If you're not using Chrome, try with that.

**Comment by BNoiZe** [comment]
I tested again and it parsed correctly. Looks like the error only occurs if you haven't exported the complete module from R20.

**Comment by Enigma644** [comment]
Cool, thanks for letting me know. I'm glad it's working :-)
